### PR TITLE
fix(alert): do not overwrite id set in htmlAttributes

### LINKED ISSUE #29704: bug: Overlays override id assigned through htmlAttributes
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

After upgrading from version 7 to 8, the ion-alerts created via the AlertController no longer have the custom ID attribute I set via the htmlAttributes property like so

``` ts
alertController.create({
    htmlAttributes: {id: 'custom-id'}
    ...
});
```

Instead, it has an id of `ion-overlay-1`.

### Expected Behavior

The ion-alert should have the custom ID

### Steps to Reproduce

1. Create a new alert via the AlertController, giving it a custom ID
2. Observe that the underlying ion-alert does not have the custom ID

### Code Reproduction URL

https://github.com/mikelhamer/ion8-alert-bug

### Ionic Info

```
[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package.json'
       
       Require stack:
       - /opt/homebrew/lib/node_modules/@ionic/cli/lib/project/index.js
       - /opt/homebrew/lib/node_modules/@ionic/cli/lib/index.js
       - /opt/homebrew/lib/node_modules/@ionic/cli/index.js
       - /opt/homebrew/lib/node_modules/@ionic/cli/bin/ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package.json'
       
       Require stack:
       - /opt/homebrew/lib/node_modules/@ionic/cli/lib/project/index.js
       - /opt/homebrew/lib/node_modules/@ionic/cli/lib/index.js
       - /opt/homebrew/lib/node_modules/@ionic/cli/index.js
       - /opt/homebrew/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI                     : 7.2.0 (/opt/homebrew/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 8.2.5
   @angular-devkit/build-angular : 18.1.0
   @angular-devkit/schematics    : 18.1.0
   @angular/cli                  : 18.1.0
   @ionic/angular-toolkit        : 11.0.1

Capacitor:

   Capacitor CLI      : 6.1.0
   @capacitor/android : not installed
   @capacitor/core    : 6.1.0
   @capacitor/ios     : not installed

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run                             : 2.0.1

System:

   NodeJS : v20.15.1 (/usr/local/bin/node)
   npm    : 9.7.1
   OS     : macOS Monterey

```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by mikelhamer**
Issue number: resolves #29704

---------

## What is the current behavior?
Setting the id of an alert via htmlAttributes doesn't work due to it being overwritten by the overlay id.

## What is the new behavior?
Setting the id of an alert via htmlAttributes works.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

First time PR, long time fan. Please let me know if I missed any of the contributing guidelines, happy to change anything!

### CODE REVIEW

**Review by mikelhamer — COMMENTED** [review]
Oops. My commit message is bad here. Should just say something like "eslint fix". I didn't realize doing that also changed other things besides adding the semicolon at first

**Review by sean-perkins — APPROVED** [review]
The proposed changes function as expected in my testing. Thank you for your contribution to Ionic Framework!

For the dev team: This issue applies to more than the `ion-alert`. I think to deliver value/resolve the issue experienced by Mikel we could merge this and split the original issue to track the other overlays impacted. Then the dev team could either address those or the community could assist in fixing the remaining overlays.

**Comment by mikelhamer** [comment]
Thank you! I'd be glad to help with the remaining overlays once the original issue has been split.
