### ISSUE TITLE
bug: `elm.attachShadow is not a function` TypeError in Angular SSR app since Ionic v8.2.4

### ISSUE THREAD

**Issue by SebastianKohler** [ionic-team/ionic-framework#29751]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

Since v8.2.4 Ionic components like `ion-button` and `ion-chip` produce an `elm.attachShadow is not a function` TypeError in Angular apps with server side rendering (SSR) enabled.

The TypeError did not occur in version 8.2.2 and prior, but in every version since 8.2.4.

### Expected Behavior

No TypeError like in v8.2.2 and prior.

### Steps to Reproduce

See the code reproduction URL for a minimal app on GitHub showcasing the error (steps to run the app in the [README](https://github.com/SebastianKohler/ionic-angular-ssr-attachShadow-typeError)).

The modules-based Angular app was generated with Angular CLI version 18.1.3 with the command:

```
ng new ionic-angular-ssr-attachShadow-typeError --ssr=true --standalone=false --style=scss
```

I then added `@ionic/angular` and `@ionic/angular-server`, configured Ionic and switched to Angular’s older `browser` builder which I’m using in my actual project (and as far as I know Ionic doesn’t work in Angular standalone SSR apps using the new Vite-based `application` builder). See the commit history in the code reproduction repository for a detailed account of the code changes.

Once you have the code reproduction app running you will get the TypeError in the terminal.

### Code Reproduction URL

https://github.com/SebastianKohler/ionic-angular-ssr-attachShadow-typeError

### Ionic Info

I don’t use the Ionic CLI. Here is the info from the Angular CLI:

```
Angular CLI: 18.1.3
Node: 20.12.1
Package Manager: npm 10.7.0
OS: win32 x64

Angular: 18.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1801.3
@angular-devkit/build-angular   18.1.3
@angular-devkit/core            18.1.3
@angular-devkit/schematics      18.1.3
@schematics/angular             18.1.3
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10
```

**Comment by crufter** [comment]
This is affecting us as well - SSR cannot render the site.

**Comment by kafumanto** [comment]
Same problem here.

In addition, building my app catches the error also at compile time:

```
> ng build my-app --watch

TypeError: o.attachShadow is not a function
    at Mu (file:///[redacted]/.angular/prerender-root/d62c222d-bf22-49a2-84e2-4076e9839a1f/chunk-RESHKSIQ.mjs:2:26911)
[...]
```

**Comment by Watchwolf** [comment]
Same problem for me with the latest ionic version.

**Comment by davidquintard** [comment]
occurs even in ionic 7.2.0

**Comment by davidquintard** [comment]
no workaround ?

**Comment by kafumanto** [comment]
I suspect that no one at Ionic has been looking into bug reports for a long time...

**Comment by crufter** [comment]
Probably not applicable to most but in my case the project is a website so I solved this by removing ionic and moving to angular material...

**Comment by davidquintard** [comment]
For my part, i downgraded to ionic 8.2.2.
It works fine.

**Comment by SebastianKohler** [comment]
I also pinned version 8.2.2, which is fine for now. Thinking about moving to Angular Material, but it's so much work in the case of my project.

**Comment by SebastianKohler** [comment]
Still get the error in Ionic 8.6.0, though slightly different:

```
TypeError: this.attachShadow is not a function
    at ctor.createShadowRoot (C:\Users\xxxxxx\GitHub\ionic-angular-ssr-attachShadow-typeError\dist\app\server\main.js:1:180912)
    at proxyHostElement (C:\Users\xxxxxx\GitHub\ionic-angular-ssr-attachShadow-typeError\dist\app\server\main.js:1:241935)
    at patchElement2 (C:\Users\xxxxxx\GitHub\ionic-angular-ssr-attachShadow-typeError\dist\app\server\main.js:1:243771)
    at patchChild2 (C:\Users\xxxxxx\GitHub\ionic-angular-ssr-attachShadow-typeError\dist\app\server\main.js:1:243843)
    at patchChild2 (C:\Users\xxxxxx\GitHub\ionic-angular-ssr-attachShadow-typeError\dist\app\server\main.js:1:243933)
    at patchChild2 (C:\Users\xxxxxx\GitHub\ionic-angular-ssr-attachShadow-typeError\dist\app\server\main.js:1:243933)
    at patchChild2 (C:\Users\xxxxxx\GitHub\ionic-angular-ssr-attachShadow-typeError\dist\app\server\main.js:1:243933)
    at hydrateApp (C:\Users\xxxxxx\GitHub\ionic-angular-ssr-attachShadow-typeError\dist\app\server\main.js:1:246891)
    at hydrateAppClosure (C:\Users\xxxxxx\GitHub\ionic-angular-ssr-attachShadow-typeError\dist\app\server\main.js:1:1397098)
    at hydrateFactory (C:\Users\xxxxxx\GitHub\ionic-angular-ssr-attachShadow-typeError\dist\app\server\main.js:1:1397205)
```

**Comment by DavidBowdoin** [comment]
v8.2.2 was released a year ago and we have not been able to update since.  I hope this does not mean ionic SSR is dead in the future?  Does anyone know how to fix the ionic SSR code to work with @stencil/core > 4.20.0  I believe that is the root issue.

We depend on SSR (server side rendering) so we remain 
pinned "@ionic/angular": "8.2.2"
and overrides: "@stencil/core": "4.20.0"

**Comment by SebastianKohler** [comment]
I drilled into this with the help of `gpt-5.3-codex`. You can read what it found below. The primary target for fixing this is in Stencil, because the failing code path is in the Stencil hydrate runtime, but Ionic could also add a guard/workaround in `packages/angular-server/src/ionic-server-module.ts`. I will open a new issue with Stencil and hope they fix this, since the Ionic team doesn't seem too active about it.

## `gpt-5.3-codex` report on this bug

I investigated this further and can confirm this is a regression introduced after Ionic `8.2.2` when used with Angular SSR (`@angular/ssr` + `@ionic/angular-server`).

### What I found

- [`@ionic/angular-server`](https://github.com/ionic-team/ionic-framework/blob/main/packages/angular-server/src/ionic-server-module.ts) calls `hydrateDocument(doc, ...)` from `@ionic/core/hydrate`.
- In newer versions (e.g. `8.7.17`), hydration goes through Stencil’s [`proxyHostElement`](https://github.com/stenciljs/core/blob/main/src/hydrate/platform/proxy-host-element.ts) -> [`createShadowRoot`](https://github.com/stenciljs/core/blob/main/src/utils/shadow-root.ts) -> `this.attachShadow(...)`.
- On Angular SSR, the server `Document` is Domino-based, and those elements do not have `attachShadow`.
- Result: SSR crashes with `TypeError: this.attachShadow is not a function` as soon as an Ionic component is present on the rendered page.
- Pinning to `8.2.2` avoids the crash.

### Why 8.2.2 works

In the older hydrate path, shadow host setup used SSR-safe fallback behavior instead of directly calling `attachShadow` on the external server DOM element.

### Relevant source location

This appears to come from Stencil hydrate runtime behavior:
- `src/hydrate/platform/proxy-host-element.ts` (calls `createShadowRoot`)
- `src/utils/shadow-root.ts` (`createShadowRoot` calls `attachShadow`)

Example file:
https://github.com/stenciljs/core/blob/4d322a75878cc14604c7b2cd747cdc3c17249fa5/src/hydrate/platform/proxy-host-element.ts

### Request

Could Ionic add a guard/workaround in `packages/angular-server/src/ionic-server-module.ts` (or otherwise coordinate with Stencil) so Angular SSR users are not broken on current Ionic 8.x while the Stencil-side hydrate fix is addressed?

**Comment by SebastianKohler** [comment]
Quick update after discussing this with Stencil:

I created and shared a minimal repro and got clarification from Stencil that SSR DOM environments without modern custom-element primitives (notably `attachShadow`) are considered out of scope for `hydrateDocument(...)` support. So this is not expected to be fixed upstream in Stencil for Domino-like DOMs (including Angular SSR’s current server DOM environment).

Following Stencil’s suggestion (thanks @johnjenkins), I tested an Ionic-side mitigation using `serializeShadowRoot: 'scoped'`: <https://stenciljs.com/docs/hydrate-app#serializeshadowroot>

In Ionic Angular SSR, this is the place where it applies:

```ts
// packages/angular-server/src/ionic-server-module.ts
return hydrateDocument(doc, {
  clientHydrateAnnotations: false,  // also tested true, see notes below
  serializeShadowRoot: 'scoped',
  excludeComponents: [
    // ...
  ],
});
```

Result in my repro:

- It avoids the server crash (`TypeError: this.attachShadow is not a function`).
- But it is not a complete fix in Angular SSR + Ionic: after client upgrade, rendered output is incorrect (duplicate internals, e.g. extra `<button>` outside the shadow root for `ion-button`).
- I also tested `clientHydrateAnnotations: true`; this did not resolve the client mismatch in this repro.

So the current state is:

- `declarative-shadow-dom` path crashes on server with Angular SSR DOM.
- `scoped` avoids crash but causes client/render correctness issues.

Given Stencil’s scope clarification, this now looks like an Ionic Angular SSR integration issue in `@ionic/angular-server` (how `hydrateDocument` is invoked and how SSR DOM compatibility is handled).

Could maintainers please triage this and suggest/implement a supported integration path for Angular SSR?

**Comment by SebastianKohler** [comment]
Correction/update to my previous comment (I reran everything from clean state and found my earlier conclusion on scoped+annotations was incomplete).

What I can now reproduce reliably:

1. Default path (`serializeShadowRoot` default / DSD):
- server crashes with: `TypeError: this.attachShadow is not a function`

2. Scoped path:
```ts
hydrateDocument(doc, {
  serializeShadowRoot: 'scoped',
  clientHydrateAnnotations: true,
  // ...
});
```

- avoids the server crash
- and fixes the earlier duplicate-internals symptom (no extra light-DOM `<button>` after upgrade)

However, there is still a client hydration error from Angular:
`TypeError: Cannot read properties of undefined (reading 'hasAttribute')`
(stack points into Angular hydration internals / `ngSkipHydration` checks)

Important confirmation:

- if I remove `provideClientHydration()` from the Angular app, this error disappears.

So there appear to be two separate Angular+Ionic SSR integration issues:

- server-side DSD incompatibility with current Angular SSR DOM (`attachShadow` missing)
- client-side Angular hydration mismatch after Ionic SSR processing (even when scoped+annotations is used)

Given Stencil’s scope clarification, this still looks like an Ionic Angular SSR integration problem in `@ionic/angular-server` (option defaults and hydration compatibility with Angular SSR/client hydration).

I pushed a branch with a minimal diagnostic patch (`IonicServerScopedModule`) showing the scoped+annotations behavior and remaining Angular hydration error: <https://github.com/SebastianKohler/ionic-angular-ssr-attachShadow-typeError/commit/a11b419f02a5939457a712b60d7a42e1f023153a>

**Comment by SebastianKohler** [comment]
Follow-up with new findings from [Stencil investigation](https://github.com/stenciljs/core/issues/6605#issuecomment-3944425342):

The Angular client error (`TypeError: Cannot read properties of undefined (reading 'hasAttribute')`) appears to be caused by a Stencil non-shadow patching bug affecting `.children/.childNodes` (notably with `ion-app`), which was fixed in Stencil `4.40.0`. Ionic `8.7.17` ships Stencil `4.38.0`.

This suggests a concrete Ionic fix path:
1. In `@ionic/angular-server`, use `serializeShadowRoot: 'scoped'`, and
2. Set `clientHydrateAnnotations: true`.
3. Upgrade Ionic’s bundled Stencil runtime to `>= 4.40.0`.

**Comment by SebastianKohler** [comment]
Completed in <https://github.com/ionic-team/ionic-framework/pull/30967>.
