### PR TITLE
fix(toast): allow color for translucent toast

### LINKED ISSUE #27567: bug: Toast color setting is wrong when translucent is true
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Toast background color of the toast that appears is always white.

### Expected Behavior

The background color of the toast follows the set color.

### Steps to Reproduce

1. Create a new project.
2. Add the toast component.
4. Set translucent to true.
5. Set the color.
6. Run to Web.
7. Click the button.

### Code Reproduction URL

https://github.com/angelofan/ionic-toast-color-test

### Ionic Info

Output after running `ionic info`:
```
[ERROR] Invalid project type: angular-standalone (project config: .\ionic.config.json).

        Project type must be one of: angular, react, vue, ionic-angular, ionic1, custom

Bad project type: undefined
```

After I manually modified `type` to `angular` in `ionic.config.json`. Output after running `ionic info`:
```
[WARN] Error loading @ionic/angular package.json: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package' is
       not defined by "exports" in D:\myrepo\ionic-toast-color-test\node_modules\@ionic\angular\package.json
[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'

       Require stack:
       - C:\Users\Administrator\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js    
       - C:\Users\Administrator\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\Administrator\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\Administrator\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package'

       Require stack:
       - C:\Users\Administrator\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\Administrator\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\Administrator\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\Administrator\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic

Ionic:

   Ionic CLI                     : 6.20.8 (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : not installed
   @angular-devkit/build-angular : 16.0.3
   @angular-devkit/schematics    : 16.0.3
   @angular/cli                  : 16.0.3
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.0.4
   @capacitor/android : not installed
   @capacitor/core    : 5.0.4
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.13.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.19.3
   OS     : Windows 10

```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by mapsandapps**
Issue number: resolves #27567

---------

## What is the current behavior?
Translucent toasts do not have the appropriate background color when the `color` property is set on the toast.

Screenshot 2023-06-14 at 5 46 45 PM

## What is the new behavior?

- Translucent toasts can have a background color based on the `color` property of the toast.

Screenshot 2023-06-14 at 5 46 28 PM

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Note: Translucent toasts are only available in `ios` mode.

### CODE REVIEW

File: core/src/components/toast/toast.ios.scss [hunk 1]
```diff
@@ -30,6 +30,10 @@
     background: $toast-ios-translucent-background-color;
     backdrop-filter: $toast-ios-translucent-filter;
   }
+
+  :host(.ion-color.toast-translucent) .toast-wrapper {
+    background: rgba(var(--ion-color-base-rgb, 255, 255, 255), $toast-ios-translucent-background-color-alpha);
```
Comment (thetaPC) [inline core/src/components/toast/toast.ios.scss:35]: What was the reasoning to not use the `current-color` [function](https://github.com/ionic-team/ionic-framework/blob/d3232dcc007738fae851660bd818c8056b48b7d2/core/src/themes/ionic.functions.color.scss#L7)?

```scss
:host(.ion-color.toast-translucent) .toast-wrapper {
  background: #{current-color(base, $toast-ios-translucent-background-color-alpha)};
}
```

Comment (mapsandapps) [reply core/src/components/toast/toast.ios.scss:35]: only because i didn't realize that `current-color` can accept an alpha 🙃

**Review by thetaPC — APPROVED** [review]
LGTM
