### ISSUE TITLE
bug: FileReader onloadend works on browser but not in mobile

### ISSUE THREAD

**Issue by almaz1213** [ionic-team/ionic-framework#25743]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

i would like back to [bug](https://github.com/ionic-team/ionic-framework/issues/25734) because:
There is the same question in the Ionic Forums, but no answers. it seems to related zone.js of angular that included in ionic. So, it's likely issue releted to ionic release. Please, check it more deep

### Expected Behavior

it shoul work in mobile, too

### Steps to Reproduce

```
....
download() {
      let r = new FileReader();
        r.onloadend = () => {
          console.error('it never happens on ionic android app');
          this.c.saveImg(this.c.sideDialogs[this.dialogKey].title + '.png', null, r.result as string, res => {
            try {
              this.c.msg(res.uri)
            } catch (e) {
              this.c.err(res)
            }
          })
        }
        r.readAsDataURL(this.qrImgBlob);
....
```

### Ionic Info

Ionic:

Ionic CLI : 6.20.1 (/home/diamo/.nvm/versions/node/v16.15.1/lib/node_modules/@ionic/cli)
Ionic Framework : @ionic/angular 6.1.12
@angular-devkit/build-angular : 14.0.3
@angular-devkit/schematics : 14.0.3
@angular/cli : 14.0.3
@ionic/angular-toolkit : 6.1.0

Capacitor:

Capacitor CLI : 3.6.0
@capacitor/android : 3.6.0
@capacitor/core : 3.6.0
@capacitor/ios : not installed

Utility:

cordova-res : not installed globally
native-run : 1.6.0

System:

NodeJS : v16.15.1 (/home/diamo/.nvm/versions/node/v16.15.1/bin/node)
npm : 8.13.1
OS : Linux 5.4

**Comment by almaz1213** [comment]
it's happening after update ionic to 6.x. there was no that bug in ionic 5

**Comment by almaz1213** [comment]
Image().onload also never is fired in ionic 6. i thick the same reasone as with FileReader!

**Comment by almaz1213** [comment]
maybe it's happening when we update Gradle plugin, change jcentral() to mavenCentral() in capacitor plugins and update capacitor dependencies as android studio suggests. let me check more..

**Comment by almaz1213** [comment]
deleted android dir and made: npx cap add android .

building in android studio:
```
> Task :capacitor-cordova-android-plugins:compileDebugJavaWithJavac FAILED
/home/diamo/eclipse_ws/iol/bridles/ionic_test/android/capacitor-cordova-android-plugins/src/main/java/org/apache/cordova/file/FileUtils.java:39: error: cannot find symbol
import org.apache.cordova.CordovaPluginPathHandler;
                         ^
  symbol:   class CordovaPluginPathHandler
  location: package org.apache.cordova
/home/diamo/eclipse_ws/iol/bridles/ionic_test/android/capacitor-cordova-android-plugins/src/main/java/org/apache/cordova/file/FileUtils.java:1267: error: cannot find symbol
    public CordovaPluginPathHandler getPathHandler() {
           ^
  symbol:   class CordovaPluginPathHandler
  location: class FileUtils
/home/diamo/eclipse_ws/iol/bridles/ionic_test/android/capacitor-cordova-android-plugins/src/main/java/org/apache/cordova/file/FileUtils.java:1339: error: cannot find symbol
        return new CordovaPluginPathHandler(pathHandler);
                   ^
  symbol:   class CordovaPluginPathHandler
  location: class FileUtils
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors


```

**Comment by almaz1213** [comment]
will try to migrate to capacitor 4

**Comment by almaz1213** [comment]
updated capacitor to version 4. it did not solve the issue. no problems in small differnet app. in the real whole app the same problem. probably some conflicts in zone.js of other involved node package...

**Comment by almaz1213** [comment]
need resolve zone.js version conflicts of involved npm packages
