### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by syedareebshah** [ionic-team/ionic-framework#27587]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When I Create an Ionic react project with list example, it runs fine on the web, android, and ios, but when I create a blank project, it failed on Android and ios, After updating Java to v17, now it also runs on Android but still fails on IOS, I am working with ionic react and capacitor.

### Expected Behavior

I must run smoothly and fine on All supported Platforms including IOS.

### Steps to Reproduce

1. Create an empty blank ionic react app.
2. follow ios guide
3. error pops 

### Code Reproduction URL

https://github.com/areeb-gsoftconsulting/ionicapp

### Ionic Info

Error loading @capacitor/android package.json: Error: Cannot find module
       '@capacitor/android/package.json'
       
       Require stack:
       - /usr/local/lib/node_modules/@ionic/cli/lib/project/index.js
       - /usr/local/lib/node_modules/@ionic/cli/lib/index.js
       - /usr/local/lib/node_modules/@ionic/cli/index.js
       - /usr/local/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI       : 7.1.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 7.0.10

Capacitor:

   Capacitor CLI      : 5.0.4
   @capacitor/android : not installed
   @capacitor/core    : 5.0.4
   @capacitor/ios     : 5.0.4

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v20.2.0 (/usr/local/Cellar/node/20.2.0/bin/node)
   npm    : 9.6.6
   OS     : macOS Monterey

**Comment by sean-perkins** [comment]
@syedareebshah what is the error that you are experiencing with your reproduction? 

I see the error mentioned for `ionic info`, but that is related to not having `@capacitor/android` as a project dependency (e.g. the reproduction has `@capacitor/ios`: https://github.com/areeb-gsoftconsulting/ionicapp/blob/master/package.json#L18).

**Comment by areeb-gsoftconsulting** [comment]
@sean-perkins Did you try to run my repo code on IOS? This is just a new boilerplate with no change, just followed steps to run on IOS, i am going to paste all the terminal information that i got after running on IOS. **Why i am not able to run on IOS.**



ionic capacitor run ios -l --external
? Which device would you like to target? iPhone 11 Pro (simulator) (F59653BD-8B1
D-46E7-B9B6-0B8042ED7056)
> capacitor sync ios
[capacitor] ✔ Copying web assets from dist to ios/App/App/public in 24.51ms
[capacitor] ✔ Creating capacitor.config.json in ios/App/App in 1.30ms
[capacitor] ✔ copy ios in 46.06ms
[capacitor] ✔ Updating iOS plugins in 4.99ms
[capacitor] [info] Found 4 Capacitor plugins for ios:
[capacitor]        @capacitor/app@5.0.2
[capacitor]        @capacitor/haptics@5.0.2
[capacitor]        @capacitor/keyboard@5.0.2
[capacitor]        @capacitor/status-bar@5.0.2
[capacitor] ✔ Updating iOS native dependencies with pod install in 2.97s
[capacitor] ✔ update ios in 3.03s
[capacitor] [info] Sync finished in 3.435s
> vite --host=0.0.0.0 --port=8100
[vite]   ➜  Local:   http://localhost:8100/
[vite]   ➜  Network: http://192.168.1.16:8100/
[vite]   ➜  press h to show help

[INFO] Development server running!
       
       Local: http://localhost:8100
       External: http://192.168.1.16:8100
       
       Use Ctrl+C to quit this process

> capacitor run ios --no-sync --target F59653BD-8B1D-46E7-B9B6-0B8042ED7056
[capacitor] ✖ Running xcodebuild - failed!
[capacitor] [error] Command line invocation:
[capacitor]         /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace App.xcworkspace -scheme App -configuration Debug -destination id=F59653BD-8B1D-46E7-B9B6-0B8042ED7056 -derivedDataPath /Users/macuser/Desktop/ionicLearning/ionicapp/ios/DerivedData/F59653BD-8B1D-46E7-B9B6-0B8042ED7056
[capacitor]         
[capacitor]         User defaults from command line:
[capacitor]         IDEDerivedDataPathOverride = /Users/macuser/Desktop/ionicLearning/ionicapp/ios/DerivedData/F59653BD-8B1D-46E7-B9B6-0B8042ED7056
[capacitor]         IDEPackageSupportUseBuiltinSCM = YES
.
.
.
.
write-file /Users/macuser/Desktop/ionicLearning/ionicapp/ios/DerivedData/F59653BD-8B1D-46E7-B9B6-0B8042ED7056/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Capacitor.build/Objects-normal/x86_64/Capacitor.LinkFileList
[capacitor]         
[capacitor]         ** BUILD FAILED **
[capacitor]         
[capacitor]         
[capacitor]         The following build commands failed:
[capacitor]         CompileSwift normal x86_64 /Users/macuser/Desktop/ionicLearning/ionicapp/node_modules/@capacitor/ios/Capacitor/Capacitor/AppUUID.swift (in target 'Capacitor' from project 'Pods')
[capacitor]         CompileSwift normal x86_64 /Users/macuser/Desktop/ionicLearning/ionicapp/node_modules/@capacitor/ios/Capacitor/Capacitor/Array+Capacitor.swift (in target 'Capacitor' from project 'Pods')
[capacitor]         CompileSwift normal x86_64 /Users/macuser/Desktop/ionicLearning/ionicapp/node_modules/@capacitor/ios/Capacitor/Capacitor/CapacitorBridge.swift (in target 'Capacitor' from project 'Pods')
[capacitor]         CompileSwift normal x86_64 /Users/macuser/Desktop/ionicLearning/ionicapp/node_modules/@capacitor/ios/Capacitor/Capacitor/Plugins/CapacitorCookieManager.swift (in target 'Capacitor' from project 'Pods')
[capacitor]         CompileSwift normal x86_64 /Users/macuser/Desktop/ionicLearning/ionicapp/node_modules/@capacitor/ios/Capacitor/Capacitor/Plugins/CapacitorCookies.swift (in target 'Capacitor' from project 'Pods')
[capacitor]         CompileSwift normal x86_64 /Users/macuser/Desktop/ionicLearning/ionicapp/node_modules/@capacitor/ios/Capacitor/Capacitor/CapacitorExtension.swift (in target 'Capacitor' from project 'Pods')
[capacitor]         CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler (in target 'Capacitor' from project 'Pods')
[capacitor]         (7 failures)
[capacitor]         
[ERROR] An error occurred while running subprocess capacitor.
        
        capacitor run ios --no-sync --target
        F59653BD-8B1D-46E7-B9B6-0B8042ED7056 exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more
        information.

**Comment by syedareebshah** [comment]
@sean-perkins Did you try to run my repo code on IOS? This is just a new boilerplate with no change, just followed steps to run on IOS, i am going to paste all the terminal information that i got after running on IOS. **Why i am not able to run on IOS.**



ionic capacitor run ios -l --external
? Which device would you like to target? iPhone 11 Pro (simulator) (F59653BD-8B1
D-46E7-B9B6-0B8042ED7056)
> capacitor sync ios
[capacitor] ✔ Copying web assets from dist to ios/App/App/public in 24.51ms
[capacitor] ✔ Creating capacitor.config.json in ios/App/App in 1.30ms
[capacitor] ✔ copy ios in 46.06ms
[capacitor] ✔ Updating iOS plugins in 4.99ms
[capacitor] [info] Found 4 Capacitor plugins for ios:
[capacitor]        @capacitor/app@5.0.2
[capacitor]        @capacitor/haptics@5.0.2
[capacitor]        @capacitor/keyboard@5.0.2
[capacitor]        @capacitor/status-bar@5.0.2
[capacitor] ✔ Updating iOS native dependencies with pod install in 2.97s
[capacitor] ✔ update ios in 3.03s
[capacitor] [info] Sync finished in 3.435s
> vite --host=0.0.0.0 --port=8100
[vite]   ➜  Local:   http://localhost:8100/
[vite]   ➜  Network: http://192.168.1.16:8100/
[vite]   ➜  press h to show help

[INFO] Development server running!
       
       Local: http://localhost:8100
       External: http://192.168.1.16:8100
       
       Use Ctrl+C to quit this process

> capacitor run ios --no-sync --target F59653BD-8B1D-46E7-B9B6-0B8042ED7056
[capacitor] ✖ Running xcodebuild - failed!
[capacitor] [error] Command line invocation:
[capacitor]         /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace App.xcworkspace -scheme App -configuration Debug -destination id=F59653BD-8B1D-46E7-B9B6-0B8042ED7056 -derivedDataPath /Users/macuser/Desktop/ionicLearning/ionicapp/ios/DerivedData/F59653BD-8B1D-46E7-B9B6-0B8042ED7056
[capacitor]         
[capacitor]         User defaults from command line:
[capacitor]         IDEDerivedDataPathOverride = /Users/macuser/Desktop/ionicLearning/ionicapp/ios/DerivedData/F59653BD-8B1D-46E7-B9B6-0B8042ED7056
[capacitor]         IDEPackageSupportUseBuiltinSCM = YES
.
.
.
.
write-file /Users/macuser/Desktop/ionicLearning/ionicapp/ios/DerivedData/F59653BD-8B1D-46E7-B9B6-0B8042ED7056/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Capacitor.build/Objects-normal/x86_64/Capacitor.LinkFileList
[capacitor]         
[capacitor]         ** BUILD FAILED **
[capacitor]         
[capacitor]         
[capacitor]         The following build commands failed:
[capacitor]         CompileSwift normal x86_64 /Users/macuser/Desktop/ionicLearning/ionicapp/node_modules/@capacitor/ios/Capacitor/Capacitor/AppUUID.swift (in target 'Capacitor' from project 'Pods')
[capacitor]         CompileSwift normal x86_64 /Users/macuser/Desktop/ionicLearning/ionicapp/node_modules/@capacitor/ios/Capacitor/Capacitor/Array+Capacitor.swift (in target 'Capacitor' from project 'Pods')
[capacitor]         CompileSwift normal x86_64 /Users/macuser/Desktop/ionicLearning/ionicapp/node_modules/@capacitor/ios/Capacitor/Capacitor/CapacitorBridge.swift (in target 'Capacitor' from project 'Pods')
[capacitor]         CompileSwift normal x86_64 /Users/macuser/Desktop/ionicLearning/ionicapp/node_modules/@capacitor/ios/Capacitor/Capacitor/Plugins/CapacitorCookieManager.swift (in target 'Capacitor' from project 'Pods')
[capacitor]         CompileSwift normal x86_64 /Users/macuser/Desktop/ionicLearning/ionicapp/node_modules/@capacitor/ios/Capacitor/Capacitor/Plugins/CapacitorCookies.swift (in target 'Capacitor' from project 'Pods')
[capacitor]         CompileSwift normal x86_64 /Users/macuser/Desktop/ionicLearning/ionicapp/node_modules/@capacitor/ios/Capacitor/Capacitor/CapacitorExtension.swift (in target 'Capacitor' from project 'Pods')
[capacitor]         CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler (in target 'Capacitor' from project 'Pods')
[capacitor]         (7 failures)
[capacitor]         
[ERROR] An error occurred while running subprocess capacitor.
        
        capacitor run ios --no-sync --target
        F59653BD-8B1D-46E7-B9B6-0B8042ED7056 exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more
        information.

**Comment by sean-perkins** [comment]
@syedareebshah I am able to successfully run your provided reproduction with these commands and receive no errors:

```
git clone https://github.com/areeb-gsoftconsulting/ionicapp.git
cd ionicapp
npm install
npm run build
npx cap copy ios
npx cap sync ios
npx cap open ios
```

& then running through xCode. 

I am going to close this issue as it isn't an issue with Ionic Framework (the web UI). I would recommend if you continue to experience problems to make sure your Capacitor CLI is up to date and asking support related questions in the Capacitor Discord.

If any documentation is out of date/incorrect, please report that issue either on Ionic Docs (ionicframework.com) or the Capacitor docs (capacitor.js.com).

Thanks!
