### ISSUE TITLE
bug: Toast color setting is wrong when translucent is true

### ISSUE THREAD

**Issue by angelofan** [ionic-team/ionic-framework#27567]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Toast background color of the toast that appears is always white.

### Expected Behavior

The background color of the toast follows the set color.

### Steps to Reproduce

1. Create a new project.
2. Add the toast component.
4. Set translucent to true.
5. Set the color.
6. Run to Web.
7. Click the button.

### Code Reproduction URL

https://github.com/angelofan/ionic-toast-color-test

### Ionic Info

Output after running `ionic info`:
```
[ERROR] Invalid project type: angular-standalone (project config: .\ionic.config.json).

        Project type must be one of: angular, react, vue, ionic-angular, ionic1, custom

Bad project type: undefined
```

After I manually modified `type` to `angular` in `ionic.config.json`. Output after running `ionic info`:
```
[WARN] Error loading @ionic/angular package.json: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package' is
       not defined by "exports" in D:\myrepo\ionic-toast-color-test\node_modules\@ionic\angular\package.json
[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'

       Require stack:
       - C:\Users\Administrator\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js    
       - C:\Users\Administrator\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\Administrator\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\Administrator\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package'

       Require stack:
       - C:\Users\Administrator\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\Administrator\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\Administrator\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\Administrator\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic

Ionic:

   Ionic CLI                     : 6.20.8 (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : not installed
   @angular-devkit/build-angular : 16.0.3
   @angular-devkit/schematics    : 16.0.3
   @angular/cli                  : 16.0.3
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.0.4
   @capacitor/android : not installed
   @capacitor/core    : 5.0.4
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.13.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.19.3
   OS     : Windows 10

```

**Comment by angelofan** [comment]
The translucent style `:host(.toast-translucent) .toast-wrapper` overrides the toast color style `:host(.ion-color) .toast-wrapper`.

```
:host(.toast-translucent) .toast-wrapper {
      background: rgba(var(--ion-background-color-rgb, 255, 255, 255), 0.8);
      backdrop-filter: saturate(180%) blur(20px);
}

:host(.ion-color) .toast-wrapper {
     background: var(--ion-color-base);
}
```

**Comment by liamdebeasi** [comment]
Thanks for the report. I can reproduce this. It looks like we need to account for `.ion-color` with the translucent styles:

```css
:host(.toast-translucent) .toast-wrapper {
  background: rgba(var(--ion-background-color-rgb, 255, 255, 255), 0.8);
  backdrop-filter: saturate(180%) blur(20px);
}

:host(.ion-color) .toast-wrapper {
  background: var(--ion-color-base);
}

:host(.ion-color.toast-translucent) .toast-wrapper {
  background: rgba(var(--ion-color-base-rgb, 255, 255, 255), 0.8);
}
```

**Comment by mapsandapps** [comment]
Thanks for reporting this issue! This has been resolved via #27652 and will be available in an upcoming release of Ionic.
