### ISSUE TITLE
bug: react, modal does not wait for contents to mount before opening

### ISSUE THREAD

**Issue by galash13** [ionic-team/ionic-framework#27343]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When opening the modal, there's a high chance the animation lags and is not smooth. 

### Expected Behavior

When opening the modal, the animation should never lag. It should always be smooth.

### Steps to Reproduce

1. Clone the repo available at [https://github.com/galash13/ionic-react-modal-issue](https://github.com/galash13/ionic-react-modal-issue)
2. Open the Xcode project and run on a device or simulator
3. Try opening/closing the modal. If the issue doesn't immediately appear, try again more times and it will. 

The modal is being opened and closed with the `isOpen` method described in the [docs](https://ionicframework.com/docs/api/modal#using-isopen)

Below you can find a few screen recordings of the issue on different devices

https://user-images.githubusercontent.com/56839513/235364027-95dbe817-a8a5-4984-9710-9649db649647.mp4

https://user-images.githubusercontent.com/56839513/235364035-a158a0e1-9f5f-43be-a309-c3024014fd0d.mp4

https://user-images.githubusercontent.com/56839513/235364847-28cbcbff-1b86-4e93-8511-c8564595e475.mp4

### Code Reproduction URL

https://github.com/galash13/ionic-react-modal-issue

### Ionic Info

[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package.json'
       
       Require stack:
       - /Users/galash13/.nvm/versions/node/v19.9.0/lib/node_modules/@ionic/cli/lib/project/index.js
       - /Users/galash13/.nvm/versions/node/v19.9.0/lib/node_modules/@ionic/cli/lib/index.js
       - /Users/galash13/.nvm/versions/node/v19.9.0/lib/node_modules/@ionic/cli/index.js
       - /Users/galash13/.nvm/versions/node/v19.9.0/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI       : 7.0.1 (/Users/galash13/.nvm/versions/node/v19.9.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 7.0.4

Capacitor:

   Capacitor CLI      : 4.8.0
   @capacitor/android : not installed
   @capacitor/core    : 4.8.0
   @capacitor/ios     : 4.8.0

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v19.9.0 (/Users/galash13/.nvm/versions/node/v19.9.0/bin/node)
   npm    : 9.6.3
   OS     : macOS 13 Ventura

**Comment by noskovvkirill** [comment]
We experience the same issue and it stops us from upgrading to v7

**Comment by liamdebeasi** [comment]
As a temporary workaround you can set `keepContentsMounted="true"` while we work to resolve this issue..The problem here is that the inner contents of the modal is not mounted before the animation starts.

**Comment by liamdebeasi** [comment]
Here is a dev build with a proposed fix: `7.0.5-dev.11682960862.1dc991b3`

Install Example:

```
npm install @ionic/react@7.0.5-dev.11682960862.1dc991b3 @ionic/react-router@7.0.5-dev.11682960862.1dc991b3
```

**Comment by galash13** [comment]
gave the dev build a quick test on a simulator and a device in my app and the issue is fixed! 🙌
